### ISSUE TITLE
pwm waveshape unstable every few second after setup a small duty value(5% etc) 

### ISSUE THREAD

**Issue by skcks** [nochkin/multipwm#2]
when setup a small duty value(5% etc) ,  pwm waveshape become unstable every few second.  how to solve this problem?

**Comment by nochkin** [comment]
Could be a bug. The code is new.
I don't have a logic analyzer to check it. Can you please provide screenshots?

**Comment by skcks** [comment]
the same problem exist in newpwm,   it could be detect by using oscilloscope .

**Comment by nochkin** [comment]
The "newpwm" is not my code, I can't say anything for it. The "multipwm" is not related to it.
Can you please provide a screenshot of the distortion you saw?

**Comment by skcks** [comment]
ok, I will post the screenshot of oscilloscope later.

**Comment by skcks** [comment]
Screenshot from oscilloscope :
![dist](https://user-images.githubusercontent.com/2995881/36630393-a71653fa-19a0-11e8-965a-e7e7e0a037fb.gif)


run test in my project, my project use some COMPONENTS defined in Makefile

```
EXTRA_COMPONENTS = $(abspath ./components/cjson) \
		extras/spiffs \
		extras/onewire \
                extras/ds18b20 \
		extras/sntp \
		extras/mdnsresponder \
		extras/mbedtls \
		extras/httpd
```

some code used multipwm, always get freq 76Hz ignored PWM_FREQ 
```
        #define PWM_FREQ 500

        ....

        multipwm_init(&pwm_info);
	multipwm_set_freq(&pwm_info, PWM_FREQ);

	for (int i = 0; i < pin_count; i++) {
		multipwm_set_pin(&pwm_info, i, pins[i]);
	}

	BR_LOGI(TAG, "gpio setup finish\n");

	multipwm_start(&pwm_info);
```
![2](https://user-images.githubusercontent.com/2995881/36630564-8bbfd89e-19a3-11e8-90d3-88a3c5c17cff.png)

**Comment by nochkin** [comment]
Great. Thank you for the screenshots.
Seems like something else is taking the interrupt resources and that breaks things. I'll try to get a hold for a logic analyzer so I could debug it.
Meanwhile, is it possible to minimize your project to see if another library may cause the conflict? I know printf's may distort it so if you could temporary remove/comment it, then would be a good test too.

**Comment by skcks** [comment]
run examples/multipwm_test.c is unstable also, the pwm wave delay. the freq become 1.3khz.
![dist-ex](https://user-images.githubusercontent.com/2995881/36638023-9c34d6cc-1a23-11e8-9c90-05847c7b2099.gif)

**Comment by nochkin** [comment]
Thanks for checking and providing the relevant information. I'll take another look when I get the logic analyzer so I can debug the issue.
I have some ideas.

**Comment by nochkin** [comment]
Sorry for delay. I got my logic analyzer and was able to replicate the issue more or less.
I believe I fixed the issue. I just need more testing to make sure this works well.

I will keep you updated. Stay tuned, don't go too far.

**Comment by skcks** [comment]
@nochkin god job!!!

**Comment by xfce** [comment]
does this function OK now?

**Comment by nochkin** [comment]
@xfce,
Besides setting the frequency, it works.
I could not exactly replicate the issue, but at least I know this is related to setting a new frequency.

Unfortunately, investigation took much longer than expected due to limited tools I have. But I still plan to make it work.

**Comment by FelipeCrispim** [comment]
Hi,
I have downloaded the newest version, but I'm still facing that instability. What could I do?

**Comment by FelipeCrispim** [comment]
Hi,
I have downloaded the newest version, but I'm still facing that instability. I have tried to set the frequency, for example, to 1kHz but it didn't solve the instability...
What could I do?

**Comment by nochkin** [comment]
As I mentioned before, setting the frequency does not work. I need to fix that issue.
When I don't set the frequency at all, it works on things like normal motors, LEDs and simple things like that.

**Comment by SmartArduino** [comment]
does this function OK now?

**Comment by nochkin** [comment]
Most of the current development moved onto ESP32 now where PWM is part of the chip.
The original esp-open-rtos is not being actively supported due to this.

I believe if you don't see the frequency, the lib should still behave properly.
If you have PR for improvement, feel free to submit it.
